# Generated by Django 2.2.6 on 2019-10-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '__first__'),
        ('doador', '0002_auto_20191018_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.IntegerField(max_length=10, verbose_name='Quantidade')),
                ('doador', models.ManyToManyField(to='doador.Doador', verbose_name='doador')),
                ('localizacao_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizaçao', to='escola.Escola', verbose_name='localizaçao')),
            ],
        ),
    ]
