# Generated by Django 2.2.6 on 2019-10-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='localizacao',
            field=models.CharField(max_length=50, verbose_name='localizaçao'),
        ),
    ]
